// ===== GenerateToken =====
export const CREATE_AUTH = "CREATE_AUTH";
export const AUTH_USER_RESPONSE = "AUTH_USER_RESPONSE";
export const LOGOUT_USER = "LOGOUT_USER";



// REGISTER
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_RESPONSE = "REGISTER_USER_RESPONSE";

// OTP VERIFY
export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_RESPONSE = "VERIFY_OTP_RESPONSE";

export const CREATE_RESOLUTION = "CREATE_RESOLUTION";
export const CREATE_RESOLUTION_RESPONSE = "CREATE_RESOLUTION_RESPONSE";


export const FETCH_DASHBOARD = "FETCH_DASHBOARD";
export const CHECK_IN = "CHECK_IN"; 



